# Generated by Django 4.0.3 on 2022-04-11 06:20

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobile', models.BigIntegerField(unique=True)),
                ('course', multiselectfield.db.fields.MultiSelectField(choices=[('python', 'python'), ('Django', 'Django'), ('MySQL', 'MySQL')], max_length=19)),
                ('location', multiselectfield.db.fields.MultiSelectField(choices=[('hyderabad', 'hyderabad'), ('pune', 'pune'), ('mumbai', 'mumbai')], max_length=21)),
                ('start_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
